### PR TITLE
feat: shard edition

### PR DESCRIPTION
**Pull request by saurav0705**

### CODE REVIEW

**Comment by cwbusacker** [comment]
I'm having a hard time understanding what this PR is changing

**Comment by saurav0705** [comment]
@cwbusacker this pr handles if you are running a check in shards

**Comment by cwbusacker** [comment]
> @cwbusacker this pr handles if you are running a check in shards

What are shards?

**Comment by saurav0705** [comment]
@cwbusacker 
shards is not the correct word i mean to say matrix if you run a job using a matrix ideally every matrix is unique so it should handle that also

**Pull request closed without merging**
